export interface MarketBusiness {
    id: number;
    name: string;
    type: "physical" | "digital";
    category: "Food" | "Health" | "Education" | "Fashion" | "Services";
    location: [number, number]; // [lat, lng]
    country: string;
    city: string;
    acceptsBitcoin: boolean;
    description: string;
  }
  
  export const businesses: MarketBusiness[] = [
    {
      id: 1,
      name: "Cafe Libertad",
      type: "physical",
      category: "Food",
      location: [19.4326, -99.1332], // Mexico City
      country: "Mexico",
      city: "CDMX",
      acceptsBitcoin: true,
      description: "Local café in Roma Norte accepting Bitcoin and Lightning.",
    },
    {
      id: 2,
      name: "Bitcoin Chic",
      type: "physical",
      category: "Fashion",
      location: [34.0522, -118.2437], // Los Angeles
      country: "USA",
      city: "Los Angeles",
      acceptsBitcoin: true,
      description: "Sustainable fashion boutique for the modern Bitcoiner.",
    },
    {
      id: 3,
      name: "Salud Digital",
      type: "digital",
      category: "Health",
      location: [0, 0],
      country: "Remote",
      city: "Online",
      acceptsBitcoin: true,
      description: "Telemedicine services for LATAM paid in BTC.",
    },
    {
      id: 4,
      name: "CryptoKids Academy",
      type: "digital",
      category: "Education",
      location: [0, 0],
      country: "Remote",
      city: "Online",
      acceptsBitcoin: true,
      description: "Bitcoin-first learning for kids across LATAM.",
    },
    {
      id: 5,
      name: "Tortas Lightning",
      type: "physical",
      category: "Food",
      location: [-23.5505, -46.6333], // São Paulo
      country: "Brazil",
      city: "São Paulo",
      acceptsBitcoin: true,
      description: "Street food with Lightning-fast flavor.",
    },
    {
      id: 6,
      name: "Cosmic Nails",
      type: "physical",
      category: "Fashion",
      location: [6.2442, -75.5812], // Medellín
      country: "Colombia",
      city: "Medellín",
      acceptsBitcoin: true,
      description: "Beauty salon accepting BTC tips.",
    },
    {
      id: 7,
      name: "MujerBit Freelance Hub",
      type: "digital",
      category: "Services",
      location: [0, 0],
      country: "Remote",
      city: "Online",
      acceptsBitcoin: true,
      description: "Latina-led digital services — design, dev, and writing.",
    },
    {
      id: 8,
      name: "BTC Pet Care",
      type: "physical",
      category: "Health",
      location: [40.7128, -74.006], // NYC
      country: "USA",
      city: "New York",
      acceptsBitcoin: true,
      description: "Veterinary clinic accepting Bitcoin for all furry needs.",
    },
  {
    id: 9,
    name: "Sabor Cripto",
    type: "physical",
    category: "Food",
    location: [25.6866, -100.3161], // Monterrey
    country: "Mexico",
    city: "Monterrey",
    acceptsBitcoin: true,
    description: "Modern taquería accepting Bitcoin and promoting financial freedom.",
  },
  {
    id: 10,
    name: "BitTango Studio",
    type: "physical",
    category: "Fashion",
    location: [-34.6037, -58.3816], // Buenos Aires
    country: "Argentina",
    city: "Buenos Aires",
    acceptsBitcoin: true,
    description: "Latina-owned tattoo & piercings studio powered by BTC.",
  },
  {
    id: 11,
    name: "Crypto Librería",
    type: "physical",
    category: "Education",
    location: [10.4806, -66.9036], // Caracas
    country: "Venezuela",
    city: "Caracas",
    acceptsBitcoin: true,
    description: "Books, zines, and radical Bitcoin knowledge for all ages.",
  },
  {
    id: 12,
    name: "Flor de Luna Spa",
    type: "physical",
    category: "Health",
    location: [-12.0464, -77.0428], // Lima
    country: "Peru",
    city: "Lima",
    acceptsBitcoin: true,
    description: "Holistic women’s wellness spa with BTC payment available.",
  },
  {
    id: 13,
    name: "BitCafé del Valle",
    type: "physical",
    category: "Food",
    location: [13.6929, -89.2182], // San Salvador
    country: "El Salvador",
    city: "San Salvador",
    acceptsBitcoin: true,
    description: "Crypto-friendly café and co-working space.",
  },
  {
    id: 14,
    name: "Cyber Botanica",
    type: "digital",
    category: "Services",
    location: [0, 0],
    country: "Remote",
    city: "Online",
    acceptsBitcoin: true,
    description: "Digital mysticism, tarot & coaching sessions via Bitcoin.",
  },
  {
    id: 15,
    name: "BTC Tutors",
    type: "digital",
    category: "Education",
    location: [0, 0],
    country: "Remote",
    city: "Online",
    acceptsBitcoin: true,
    description: "Tutoring in math, programming, and crypto onboarding.",
  },
  {
    id: 16,
    name: "Remix & Rebirth",
    type: "digital",
    category: "Fashion",
    location: [0, 0],
    country: "Remote",
    city: "Online",
    acceptsBitcoin: true,
    description: "Upcycled clothing store with BTC & Lightning checkout.",
  },
  {
    id: 17,
    name: "BitForPets",
    type: "physical",
    category: "Health",
    location: [-33.4489, -70.6693], // Santiago
    country: "Chile",
    city: "Santiago",
    acceptsBitcoin: true,
    description: "Pet food & services with Bitcoin rewards program.",
  },
  {
    id: 18,
    name: "Node Mujer",
    type: "digital",
    category: "Education",
    location: [0, 0],
    country: "Remote",
    city: "Online",
    acceptsBitcoin: true,
    description: "Education & onboarding for women in Bitcoin LATAM.",
  },
  {
    id: 19,
    name: "Tienda Satoshi",
    type: "physical",
    category: "Services",
    location: [18.7357, -70.1627], // Dominican Republic
    country: "Dominican Republic",
    city: "Santo Domingo",
    acceptsBitcoin: true,
    description: "Printing, scanning & microservices shop accepting BTC.",
  },
  {
    id: 20,
    name: "BitCeramics",
    type: "physical",
    category: "Fashion",
    location: [21.1619, -86.8515], // Cancún
    country: "Mexico",
    city: "Cancún",
    acceptsBitcoin: true,
    description: "Handmade ceramic art from the Yucatán jungle.",
  },
  {
    id: 21,
    name: "Crypto Cacao",
    type: "physical",
    category: "Food",
    location: [9.7489, -83.7534], // Costa Rica
    country: "Costa Rica",
    city: "San José",
    acceptsBitcoin: true,
    description: "Cacao drinks, chocolate workshops, and BTC beans.",
  },
  {
    id: 22,
    name: "Freedom Kitchen",
    type: "physical",
    category: "Food",
    location: [14.6349, -90.5069], // Guatemala
    country: "Guatemala",
    city: "Guatemala City",
    acceptsBitcoin: true,
    description: "Vegan café & food activism hub with BTC POS.",
  },
  {
    id: 23,
    name: "BitStreet Wear",
    type: "physical",
    category: "Fashion",
    location: [-15.7939, -47.8828], // Brasília
    country: "Brazil",
    city: "Brasília",
    acceptsBitcoin: true,
    description: "Streetwear for rebels. BTC only.",
  },
  {
    id: 24,
    name: "Casa Crypto Colectiva",
    type: "physical",
    category: "Education",
    location: [20.6597, -103.3496], // Guadalajara
    country: "Mexico",
    city: "Guadalajara",
    acceptsBitcoin: true,
    description: "Community learning center for decentralization & sovereignty.",
  },
  {
    id: 25,
    name: "BitHands Therapy",
    type: "physical",
    category: "Health",
    location: [7.1139, -73.1198], // Bucaramanga
    country: "Colombia",
    city: "Bucaramanga",
    acceptsBitcoin: true,
    description: "Massage & physiotherapy sessions paid in BTC.",
  },
  {
    id: 26,
    name: "Kawaii Crypto Goods",
    type: "digital",
    category: "Fashion",
    location: [0, 0],
    country: "Remote",
    city: "Online",
    acceptsBitcoin: true,
    description: "Latina-owned digital gift shop for cute crypto stuff.",
  },
  {
    id: 27,
    name: "NodeCreativo",
    type: "digital",
    category: "Services",
    location: [0, 0],
    country: "Remote",
    city: "Online",
    acceptsBitcoin: true,
    description: "Design, branding & content studio paid in BTC.",
  },
  {
    id: 28,
    name: "BitFixers",
    type: "physical",
    category: "Services",
    location: [4.7110, -74.0721], // Bogotá
    country: "Colombia",
    city: "Bogotá",
    acceptsBitcoin: true,
    description: "Tech repair shop that accepts Bitcoin for all services.",
  },
  {
    id: 29,
    name: "CryptoGlow Skincare",
    type: "physical",
    category: "Health",
    location: [32.7157, -117.1611], // San Diego
    country: "USA",
    city: "San Diego",
    acceptsBitcoin: true,
    description: "Natural skincare line blending science and Satoshi.",
  },
];